### ISSUE TITLE
JsonProvider parse.next question

### ISSUE THREAD

**Issue by hypersurge** [kevinresol/turnwing#5]
Tests all run as expected.

But when not running a Test / Assert scenario the `loc.get' promise does not appear to trigger next()?

From my rudimentary debug I'd say it's gettng stuck between the Json parse() and the make():
https://github.com/kevinresol/turnwing/blob/master/src/turnwing/provider/JsonProvider.hx#L41

The parse is generating Json but it doesn't find it's way to make.  Given that it works in the Test Runner I feel like I'm missing something obvious?

Or to put it more simply ... how is Manager expected to be used in a non-test build?

**Comment by kevinresol** [comment]
`.get()` gives you a tink.core.Promise which is lazy, as well as its derivatives (result of its `.next()`). You need to `.handle()` a Promise so it will actually "run"

**Comment by hypersurge** [comment]
Thank you, got there.  I didn't know Promises are lazy (historically I've been using them with @:await which, I assume, conceals the handle).  Yes, all working as expected now.
